# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'
  
#- task: DotNetCoreInstaller@0
#  inputs:
#    version: '2.1.300' # replace this value with the version that you need for your project  

steps:
- script: dotnet restore
- script: dotnet build # Include additional options such as --configuration to meet your need
- script: dotnet tool install -g dotnetsay
- script: dotnetsay
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: PublishBuildArtifacts@1
